name: planner_daily
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl: ^0.19.0
  sqflite: ^2.3.3+1
  provider: ^6.0.0
  flutter_local_notifications: ^17.2.3
  fl_chart: ^0.69.0
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  cupertino_icons: ^1.0.8


flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.png
    - assets/img/logo-no-background.png
    - assets/img/login.png
